services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Contas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  postgres:
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=Contas
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d Contas" ]
      interval: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15673:15672"

volumes:
  postgres-data:
